### ISSUE TITLE
QObject.findChild should return Optional[QObject]

### ISSUE THREAD

**Issue by deavid** [stlehmann/PyQt5-stubs#10]
https://github.com/stlehmann/PyQt5-stubs/blob/189a0497d08ddd65f46e4819f427eb2d03196589/PyQt5-stubs/QtCore.pyi#L1700

QObject.findChild can return a nullpointer, so it gets converted to None in Python.
This means the return value should change from QObject to Optional[QObject]

**Comment by sweethuman** [comment]
Also shouldn't it also return the type specified in type param, instead of QObject by default?

**Comment by altendky** [comment]
Some work available in #58.

**Comment by altendky** [comment]
Would you consider #58 to fix this?  As noted in the comments there is room for more improvement in the direction of variadic generics but as they aren't actually supported I thought any workaround like is described ought to be handled separately.

FYI @Djedouas, in case you aren't subscribed here.

**Comment by altendky** [comment]
I'm going to go ahead and close this considering it fixed by #58.  If you disagree, please do let me know what case isn't covered properly.
