### ISSUE TITLE
Enumerations should inherit from enum.IntEnum not int

### ISSUE THREAD

**Issue by altendky** [stlehmann/PyQt5-stubs#106]
https://github.com/stlehmann/PyQt5-stubs/blob/811462b34ee151b898289ae8f1de8af30c690c55/PyQt5-stubs/QtBluetooth.pyi#L158-L160

```pycon
Python 3.8.5 (default, Jul 29 2020, 21:06:26) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt5 import QtWidgets
>>> application = QtWidgets.QApplication([])
>>> from PyQt5 import QtBluetooth
>>> QtBluetooth.QBluetoothDeviceInfo.Field.__mro__
(<enum 'Field'>, <enum 'IntEnum'>, <class 'int'>, <enum 'Enum'>, <class 'object'>)
```

I presume this applies to many/most/all.

**Comment by BryceBeagle** [comment]
Oh man this will probably be a large diff.

The alpha release for PyQt6 provides this message:
> All enums are now implemented as enum.Enum (PyQt5 used enum.IntEnum for scoped enums and a custom type for traditional named enums). PyQt5 allowed an int whenever an enum was expected but PyQt6 requires the correct type.

While we're not interested in PyQt6 (yet) it does provide a good summary for the current status of enums in PyQt5.

1. Do you know what it means by a "scoped enum"
2. What "custom type" is this referring to?
3. _Should_ we type annotate everything that takes an enum to also take an `int`, after this change? It seems that's "deprecated" now

**Comment by altendky** [comment]
I should have mentioned that I found this while running `stubtest` which instead complains about:

```
/home/altendky/repos/PyQt5-stubs/venv38/bin/python /home/altendky/repos/PyQt5-stubs/venv38/bin/stubtest --allowlist stubtest.allowlist PyQt5
error: PyQt5.QtBluetooth.QBluetoothDeviceInfo.Field.__new__ is inconsistent, stub argument "x" has a default value but runtime argument does not
Stub: at line 184
Overload(def [_T] (cls: Type[_T`-1], x: Union[builtins.str, builtins.bytes, typing.SupportsInt, builtins._SupportsIndex] =) -> _T`-1, def [_T] (cls: Type[_T`-1], x: Union[builtins.str, builtins.bytes, builtins.bytearray], base: builtins.int) -> _T`-1)
Inferred signature: def (cls: Type[_T`-1], x: Union[builtins.str, typing.SupportsInt, builtins._SupportsIndex] = ..., base: builtins.int = ...)
Runtime: at line 562 in file /home/altendky/.pyenv/versions/3.8.5/lib/python3.8/enum.py
def (cls, value)

error: PyQt5.QtBluetooth.QBluetoothDeviceInfo.Field.__new__ is inconsistent, runtime does not have argument "base"
Stub: at line 184
Overload(def [_T] (cls: Type[_T`-1], x: Union[builtins.str, builtins.bytes, typing.SupportsInt, builtins._SupportsIndex] =) -> _T`-1, def [_T] (cls: Type[_T`-1], x: Union[builtins.str, builtins.bytes, builtins.bytearray], base: builtins.int) -> _T`-1)
Inferred signature: def (cls: Type[_T`-1], x: Union[builtins.str, typing.SupportsInt, builtins._SupportsIndex] = ..., base: builtins.int = ...)
Runtime: at line 562 in file /home/altendky/.pyenv/versions/3.8.5/lib/python3.8/enum.py
def (cls, value)
```

Which I haven't made sense of yet.  But I checked the `.__mro__` and noticed it was an `IntEnum` (which didn't fix the above messages).

1. I assume this refers to the enumerators being available as `module.TheEnum.an_enumerator` rather than `module.an_enumerator`.
2. Some custom type that PyQt5 uses instead of `enum.Enum` or `enum.IntEnum`.
3. If we accurately use `enum.IntEnum` as the base I think that would inherently make the `int` compatibility just work out?

And yeah, this would be big.  Potentially it's worth not doing all of them straight away in case maybe Phil gets it.  Speaking of which, do you think it's worth bringing the topic up soon?  Or should I try to get through the `stubtest` stuff first?  Or if we go really big picture we would automate the collection of nightlies (I've got a script I run locally at the moment), build a repo off of that, and trigger our builds off the nightlies for automated updates in maybe a `nightly` branch or something so we can readily see the changes Phil makes.  But probably don't wait for this I guess...  But back on topic, when do you think we should start chatting with Phil?

**Comment by BryceBeagle** [comment]
> when do you think we should start chatting with Phil?

I think now is a pretty good time to get the conversation started. I think you've resolved/recorded almost all the issues. We might want to compose a document for him, or do you think simply linking our changelog here on Github would be enough?

I also think there's a non-zero chance that Phil will postpone an overhaul of the stubs until PyQt6, but I could be wrong.

**Comment by BryceBeagle** [comment]
> 3. If we accurately use enum.IntEnum as the base I think that would inherently make the int compatibility just work out?

If a function is annotated as taking an `IntEnum`, the type checker won't accept an `int`, even though PyQt5 _will_. I'm wondering if we want to change the typing to accept both. Or, seeing that using an `int` is sort-of deprecated (being removed in PyQt6), should we not worry about it?

**Comment by altendky** [comment]
Yeah, I didn't have my head on straight there.  I dunno, I'll have to take another pass tomorrow at thinking about this.

**Comment by bluebird75** [comment]
There is no longer any IntEnum in our stubs. And enumeration are very properly checked now.
