### ISSUE TITLE
Consider using pytest-mypy-plugins

### ISSUE THREAD

**Issue by sobolevn** [stlehmann/PyQt5-stubs#11]
Hi! Thanks for this awesome project!

I am [TypedDjango](https://github.com/TypedDjango) team member, we maintain types for, well, django. And we do pretty much the same job.

For example, we also test our types the similar way as you do in [`tests/`](https://github.com/stlehmann/PyQt5-stubs/tree/master/tests). We even created a tool called [`pytest-mypy-plugins`](https://github.com/typeddjango/pytest-mypy-plugins) ([announcing post](https://sobolevn.me/2019/08/testing-mypy-types)) to help us with this task. Maybe it will be also helpful to you as well. 

That's how the simplest test looks like:

```yaml
- case: compose_two_wrong_functions
  main: |
    from returns.functions import compose

    def first(num: int) -> float:
        return float(num)

    def second(num: float) -> str:
        return str(num)

    reveal_type(compose(first, second)(1))  # N: builtins.str*
```

Ask any questions you have! 

P.S. This project was listed in [awesome-python-stubs](https://github.com/typeddjango/awesome-python-stubs) list.

**Comment by stlehmann** [comment]
@sobolevn Thanks for the hint. I will have a closer look at pytest-mypy-plugins for sure.

**Comment by bluebird75** [comment]
I had a look at the plugin. I find the syntax a bit complex and I prefer the simple Python code which we have right now for validating our stubs in tests.

If nobody is planning to use this plugin in PyQt5-stubs, we can close this issue.
