### ISSUE TITLE
Concerning overridden methods. Example: the layout-method for QWidget when using QGridLayout

### ISSUE THREAD

**Issue by dodspunkare** [stlehmann/PyQt5-stubs#111]
Since ``QWidget.layout()`` is type-hinted as ``QLayout``, the returned ``layout`` object from the call if using ``QGridLayout`` and further use, e.g. by calling ``layout.addWidget(w, row, column)``,  will produce an Unexpected Argument-error in IDEs such as PyCharm for the ``row`` and ``column`` parameters as these are not defined in ``QLayout.addWidget``-method.

Minimum code example
```
from PyQt5.Qt import QWidget
from PyQt5.Qt import QGridLayout

class ExampleWidget(QWidget):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        layout = QGridLayout()
        self.setLayout(layout)

    def setup_some_child_widget(self):
        child = QWidget()
        layout = self.layout()
        row, column = 0, 0
        layout.addWidget(child, row, column)

    # def layout(self) -> QGridLayout:
    #     return super().layout()
```

Is this possible to solve in a satisfying way?

Currently I avoid cluttering the interface with semi-errors from PyCharms code inspections by simply subclassing ``QWidget`` to some ``MyWidget``-class and overriding the ``QWidget.layout``-method and type-hinting it to ``QGridLayout``. However, this does not solve the core of the type hint issue and only push it to the level below, i.e. the``super().layout()``-call in such override.

**Comment by altendky** [comment]
The addition to make in the example code is to `cast(QGridLayout, super().layout())`.  Though, I won't call that 'satisfying' in a general sense.

If you are trying to deal with this without having a `QWidget` inheriting custom class...  I haven't explored it but my best guess yet (about which I am not optimistic) is to make `QWidget` generic against the layout though we would probably only want to do that if we can specify a default of `QLayout` and I'm not sure if we can do it without forcing use of type hint comments or changing the actual `QWidget` implementation in PyQt itself.  Hopefully someone (maybe myself) will come up with a 'satisfying' solution that works.

**Comment by BryceBeagle** [comment]
The way I get around this problem is to define a class-level annotation for the function:
```python
class ExampleWidget(QWidget):
    layout: Callable[..., QGridLayout]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        layout = QGridLayout()
        self.setLayout(layout)

    def setup_some_child_widget(self):
        child = QWidget()
        layout = self.layout()
        row, column = 0, 0
        layout.addWidget(child, row, column)
```

but you may argue that this isn't that much better

**Comment by amcmulle** [comment]
Running into this issue myself. Here is a quick example of the issue. 

```
import sys
from PyQt5.QtWidgets import *

if __name__ == "__main__":
    app = QApplication([])

    w = QWidget()

    grid = QGridLayout(w)
    grid.addWidget(QPushButton("Button one"),0,0)
    grid.addWidget(QPushButton("Button two"),0,1)
    grid.addWidget(QPushButton("Button three"),1,0)
    grid.addWidget(QPushButton("Button four"),1,1)


    w.show()
    sys.exit(app.exec_())
```

Any solutions would be much appreciated.

**Comment by bluebird75** [comment]
The issue is with Qt design. The PyQt5-stubs can not change it and workaround can only be specifics. This is also an issue of dynamic typing (the object returned by layout() has a dynamic varying type) which can not be properly captured by a static type checking mechanism.

So, we recoginize the annoyance but there is nothing we can do here.
