### ISSUE TITLE
Switch from Travis to GitHub Actions

### ISSUE THREAD

**Issue by altendky** [stlehmann/PyQt5-stubs#114]
Travis is significantly backlogged most of the time and we should stop using it.  I like GitHub Actions.  Presumably at some point I can make this happen.

https://www.traviscistatus.com/#month
![image](https://user-images.githubusercontent.com/543719/101122950-ad74b800-35c1-11eb-8ba8-c5d6977e5bb7.png)

**Comment by bluebird75** [comment]
We are fully using GitHub actions now, so closing this.
