### ISSUE TITLE
Update author and maintainer information

### ISSUE THREAD

**Issue by altendky** [stlehmann/PyQt5-stubs#133]
Changing maintainership doesn't change authorship, but perhaps @stlehmann would like their email removed?

@stlehmann, @BryceBeagle, @The-Compiler, would you like to be listed as maintainers in the package metadata?  If so, share your preferred name for such and optionally an email as well if you want it listed.  If you would rather not, please state so.

This is following from https://github.com/python-qt-tools/PyQt5-stubs/pull/132#pullrequestreview-593655307.

**Comment by BryceBeagle** [comment]
Do Python packages support more than one author? I know PyPI supports multiple maintainers, but I believe that information is stored externally to the package.

**Comment by stlehmann** [comment]
Yes, you can remove my e-mail. Even though I am the original author I wouldn' t mind if you want to change the author to python-qt-tools to point folks to this organization.

Anyway I don't see a need to add me to the maintainers list as I'm not really maintaining this package anymore.

**Comment by The-Compiler** [comment]
pytest uses:

```
author = Holger Krekel, Bruno Oliveira, Ronny Pfannschmidt, Floris Bruynooghe, Brianna Laugher, Florian Bruhin and others
```

Without any issues so far. I don't think there's a fixed format for that field. The `author_email` is a separate field though, I guess we could always leave that blank.

In any case, feel free to add me as "Florian Bruhin".

**Comment by BryceBeagle** [comment]
Ok, just add me as "Bryce Beagle" if you find a means
