### ISSUE TITLE
Missing attribute not detected and inheritance not followed ?

### ISSUE THREAD

**Issue by Djedouas** [stlehmann/PyQt5-stubs#14]
Hi,

Maybe this is not the right place to ask, if so thanks to redirect me...

Code:
```
from PyQt5.QtWidgets import QDialog
from PyQt5.QtCore import QObject

a = QDialog()
b = a.result()  # ok inferred type int
c = a.qsdf()  # should be error missing method but inferred type is any
d = a.isWidgetType()  # method of QObject, parent class of QDialog, a bool should be inferred but inferred tye is any

e = QObject()
f = e.isWidgetType()  # ok inferred type bool

class G:
    def yo(self) -> str:
        return "yo"

class H(G):
    pass

i = H()
j = i.yo()  # ok inferred type str
k = i.qsdf()  # ok error no attribute

reveal_locals()
```

mypy output is:
```
27:5: error: "H" has no attribute "qsdf"
29:1: note: Revealed local types are:
29:1: note:     a: PyQt5.QtWidgets.QDialog
29:1: note:     b: builtins.int
29:1: note:     c: Any
29:1: note:     d: Any
29:1: note:     e: PyQt5.QtCore.QObject
29:1: note:     f: builtins.bool
29:1: note:     i: test_module.H
29:1: note:     j: builtins.str
29:1: note:     k: Any
```

The question is: why does mypy does not detect these errors with PyQt objects?

I am using version 5.11.3.0 of PyQt5-stubs

Thanks

**Comment by The-Compiler** [comment]
It looks like ~~45ff4784a116b1757a3ff7581d761db6924334ad~~ some commit removed `sip.pyi` - was that intended, @stlehmann?

Since e.g. `QObject` inherits `sip.simplewrapper`, I suppose mypy now thinks it inherits `Any`, so it can't know what attributes actually exist.

**Comment by stlehmann** [comment]
Hm, in the master branch sip.pyi is still included. Which branch do you mean?

**Comment by The-Compiler** [comment]
Oh - there is a `sip.pyi` but it's outside of the `PyQt5-stubs` package, which probably causes it to not be installed at all. As an example, if you do `python3 setup.py sdist` and look at the resulting archive, it's not in there.

Given that sip gets imported as `PyQt5.sip` [since PyQt5 5.11](https://www.riverbankcomputing.com/static/Docs/PyQt5/incompatibilities.html#pyqt-v5-11) it should probably be moved inside the package, and all imports in the `.pyi` files should be adjusted accordingly?

**Comment by stlehmann** [comment]
@The-Compiler I didn't know that sip is included in the PyQt5 package now. So it seems to be a good solution to add sip.pyi to the PyQt5-stubs package.

**Comment by stlehmann** [comment]
Issue should be fixed with bd0fe7ce030e9c97fe046878351b34a8a7ec8de6

**Comment by Djedouas** [comment]
Hi and thanks for investigating!

I moved sip.pyi into PyQt5-stubs folder and changed every `import sip` into `from PyQt5 import sip` and still same result : no error on line

`c = a.qsdf()  # should be error missing method but inferred type is any`

but now every import from sip is followed correctly according to the verbose log of mypy (before sip was in the "missing" section of the meta, now it's in the "dependencies" section).

**Comment by Djedouas** [comment]
No idea for the `missing method` that should be detected but is not? :(
As a result, every class I create that inherits a QObject have this problem...

**Comment by stlehmann** [comment]
I don't know the reason why a missing method is not recogniced. However, the following works for some reason:

    QDialog.qsdf()

results in:

    error: "Type[QDialog]" has no attribute "qsdf"

No idea why this is not working for objects, though.

**Comment by Djedouas** [comment]
@stlehmann so you can reproduce the misbehavior ?

**Comment by stlehmann** [comment]
Yes I can. But I have no idea what the reason is.

**Comment by Djedouas** [comment]
ok.
Since I have the problem with QObject as well, it might come from the sip.simplewrapper inheritance...

**Comment by stlehmann** [comment]
It is strange, though, that checks on class methods work well.

**Comment by Djedouas** [comment]
Yes...
And among my tests, I found that if I inherit from a class that has `sip.simplewrapper` (e.g. `QByteArray`) as parent in `sip.pyi`, then the `missing attribute` error is found...
If I inherit from a class that has `sip.wrapper` as parent in `sip.pyi` (e.g. `QObject`), then the `missing attribute` error is **not** found...

```
class G(QByteArray):
    ...


class H(QObject):
    ...


a = G()
b = a.toHex()  # ok inferred type QByteArray
c = a.qsdf()  # ok error no attribute

d = H()
e = d.objectName()  # ok inferred type str
f = d.qsdf()  # should be error no attribute but nothing

reveal_locals()
```

```
src\sandbox\test_mypy.py:33:5: error: "G" has no attribute "qsdf"
src\sandbox\test_mypy.py:39:1: note: Revealed local types are:
src\sandbox\test_mypy.py:39:1: note:     a: sandbox.test_mypy.G
src\sandbox\test_mypy.py:39:1: note:     b: PyQt5.QtCore.QByteArray
src\sandbox\test_mypy.py:39:1: note:     c: Any
src\sandbox\test_mypy.py:39:1: note:     d: sandbox.test_mypy.H
src\sandbox\test_mypy.py:39:1: note:     e: builtins.str
src\sandbox\test_mypy.py:39:1: note:     f: Any
```

**Comment by The-Compiler** [comment]
@Djedouas I don't think that's true. This seems to work fine:

```python
class I(QEvent):
    ...

g = I(QEvent.KeyPress)
h = g.type()
f = g.qsdf()  # error, as expected

reveal_locals()
```

Do you see this with anything other than `QObject`?

**Comment by The-Compiler** [comment]
FWIW I think this affects `QObject` only, because the stubs (for whatever reason) have

```python
def __getattr__(self, name: str) -> typing.Any: ...
```

defined, which pretty much boils down to "Whatever attribute you get from a `QObject`, you get `Any` back". I guess that line should just go, and ideally someone should investigate why this is in the upstream stubs (if it is).

**Comment by Djedouas** [comment]
You're right, It's very specific to QObject. I was wrong.

OK I see... I agree with you, we ideally need someone to investigate why this line is still [in the master branch](https://github.com/stlehmann/PyQt5-stubs/blob/bc75993e839c9a5785baa9fcaa3a01557a24af31/PyQt5-stubs/QtCore.pyi#L1706)

For me, commenting this line indeed resolves my issue.
I think we can close the issue then.

**Comment by stlehmann** [comment]
@Djedouas "ideally" you would just drop a PR that resolves this issue so others can profit from your investigation ;)

**Comment by Djedouas** [comment]
Of course ;-)
But can we assume this line really is an error?

**Comment by stlehmann** [comment]
`But can we assume this line really is an error?`

I think we can. It definetly was autogenerated during compiling process. I would say if it does raise some issues we need to append explecit typing annotations.

**Comment by Djedouas** [comment]
Thanks for merging #16 👍

**Comment by The-Compiler** [comment]
The upstream `sip/QtCore/qobject.sip` has:

```cpp
    SIP_PYOBJECT __getattr__(const char *name /Encoding="UTF-8"/) const;
%MethodCode
        sipRes = qpycore_qobject_getattr(sipCpp, sipSelf, a0);
%End
```

Looking at the `qpy/QtCore/qpycore_qobject_getattr.cpp` file:

```cpp
// See if we can find an attribute in the Qt meta-type system.  This is
// primarily to support access to JavaScript (e.g. QQuickItem) so we don't
// support overloads.
PyObject *qpycore_qobject_getattr(const QObject *qobj, PyObject *py_qobj,
        const char *name)
[...]
```

So I guess that makes sense somehow, but probably should be excluded from the type annotations upstream.
