### ISSUE TITLE
Missing QtWebKit/QtWebEngine modules

### ISSUE THREAD

**Issue by The-Compiler** [stlehmann/PyQt5-stubs#15]
Looks like the stubs for all the QtWebKit and QtWebEngine modules went missing.

**Comment by stlehmann** [comment]
Yes, PyQt5 doesn't provide them anymore when compiling so I sadly had to remove them at an early stage.

**Comment by The-Compiler** [comment]
Sorry for the late answer - `PyQt5` definitely still has both of those. It looks more like your Qt didn't have them installed, so `sip` didn't build the `.pyi` files. I guess ideally we'd somehow get `sip` to spit out `.pyi` files without actually having to build the underlying C++ code, but not sure how realistic that is.

**Comment by BryceBeagle** [comment]
On Ubuntu 18.04 I only get the the following .pyi files to generate:
- QtCore.pyi
- QtDBus.pyi
- QtGui.pyi
- QtNetwork.pyi
- QtOpenGL.pyi
- QtPrintSupport.pyi
- QtSql.pyi
- QtTest.pyi
- QtWidgets.pyi
- QtXml.pyi

But on Arch, with the same PyQt5 source tar, I get everything:
- QtGui.pyi
- QtNfc.pyi
- QtQml.pyi
- QtSql.pyi
- QtSvg.pyi
- QtXml.pyi
- QtCore.pyi
- QtDBus.pyi
- QtHelp.pyi
- QtTest.pyi
- QtQuick.pyi
- QtOpenGL.pyi
- QtWebKit.pyi
- QtNetwork.pyi
- QtSensors.pyi
- QtWidgets.pyi
- QtDesigner.pyi
- QtLocation.pyi
- QtBluetooth.pyi
- QtX11Extras.pyi
- QtSerialPort.pyi
- QtWebChannel.pyi
- QtWebSockets.pyi
- QtNetworkAuth.pyi
- QtPositioning.pyi
- QtXmlPatterns.pyi
- QtPrintSupport.pyi
- QtQuickWidgets.pyi
- QtRemoteObjects.pyi
- QtWebKitWidgets.pyi

**Comment by stlehmann** [comment]
That's interesting. So maybe we should adjust the Dockerfile to use Arch-Linux instead of Ubuntu. @BryceBeagle as you already got the build going on Arch would you mind adjusting the Dockerfile?

**Comment by stlehmann** [comment]
> `PyQt5` definitely still has both of those. It looks more like your Qt didn't have them installed, so `sip` didn't build the `.pyi` files. 

That might be the case. In the buildenv Dockerfile I install Ubuntus qt5-default package. Do you know how to add QWebKit and QWebEngine on Ubuntu respectively Arch?

**Comment by BryceBeagle** [comment]
Sure, I'd be glad to look into it. 

However, I'm hesitant to use an Arch Linux-based Dockerfile because the distro doesn't make locking versions especially easy. Their repositories don't keep a very long history of packages so the Dockerfile would either need to manually modify PKGBUILDs, or just assume that the latest version of the software is always good enough. 

I'll try to get an Ubuntu Dockerfile working, or maybe use something like Alpine, which still updates regularly but also keeps old versions of software, if that's alright with you?

**Comment by stlehmann** [comment]
Sure that would be great. 👍

**Comment by The-Compiler** [comment]
> On Ubuntu 18.04 I only get the the following .pyi files to generate: [...]

Are you sure the underlying Qt modules (e.g. `libqt5webengine5`) are installed?

> Their repositories don't keep a very long history of packages

[They sure do!](https://wiki.archlinux.org/index.php/Arch_Linux_Archive) (the *entire* history)

**Comment by BryceBeagle** [comment]
> Are you sure the underlying Qt modules (e.g. `libqt5webengine5`) are installed?

You're right, they weren't installed. I never manually installed them on Arch, but they were optional dependencies of `python-pyqt5` that were pulled down

> They sure do!

After 6 years of using Arch, how did I not know this existed? 🤦 Guess that shows how often I need to downgrade -- my local cache has always been good enough.

**Comment by BryceBeagle** [comment]
I opened PR #36 for this

**Comment by The-Compiler** [comment]
Closing this as #36 was merged - thanks @BryceBeagle!
