### ISSUE TITLE
PyQt dependency

### ISSUE THREAD

**Issue by analog-cbarber** [stlehmann/PyQt5-stubs#158]
It appears that this package depends on PyQt itself. Normally this would not be a problem, but when I pip install this package into a conda environment that already has PyQt5 (5.12.3), it does not recognize that distribution and starts to download it again from pypi.

I can install using `--no-deps` but it would be nicer if there was no explicit package dependency.

**Comment by The-Compiler** [comment]
> It appears that this package depends on PyQt itself.

Can you elaborate? The `setup.py` only declares a dependency on PyQt5 for tests.

**Comment by analog-cbarber** [comment]
Hmm. I just did a pip install into my conda environment and it started to download and install pyqt5 as well.

**Comment by analog-cbarber** [comment]
Actually, this might just be a problem with the 5.12 release of Qt, which is what we are currently using.

I assume that 5.12 is what you need to go with the corresponding PyQt5 release?

**Comment by The-Compiler** [comment]
The dependency was removed in 02a0b6174ff6c7c6ca9f982947b8698c34c85537 for #25, so this was fixed for the 5.14.1.0 release.
