### ISSUE TITLE
Release more often

### ISSUE THREAD

**Issue by rr-** [stlehmann/PyQt5-stubs#163]
Right now when I install mypy it shows me about 400 errors with my project, when I install the newest stable pip package it shows around 200 errors, when I use the newest master it shows around 50 errors. After merging #162 this is going change again. Currently I can't make mypy a part of my CI pipeline because the packages are simply too old. This also discourages me from contributing to the project knowing that it will take a few months until a potential fix lands on pypi.

**Comment by altendky** [comment]
I'm sorry for the discouragement, I have been on your side of it many times.  We do need help with contributions as you are doing and we also need help with long term maintenance.  It all takes time and sadly that is limited.  I'll take a few minutes now at least to see what I can move along.

On the technical side, you can reference URLs when you need unreleased code.  If you care to share your project and how you install your dependencies, I can try to comment on how to achieve that.  I don't like doing that, but there are various cases where I need to at various points.

**Comment by bluebird75** [comment]
I have just released PyQt5-stubs 5.15.6.0  which fix many issues you may have encountered.

For your information, I am the new maintainer and I plan to do more frequent releases.
