### ISSUE TITLE
How to create a multilingual stub

### ISSUE THREAD

**Issue by 2421046322i** [stlehmann/PyQt5-stubs#211]
When I used stubs, I felt it was difficult for non native speakers to understand, so I came up with the idea of creating multilingual stubs.Could you give me some suggestions, except that I rewrite it myself

**Comment by The-Compiler** [comment]
I don't follow. Stubs are type information for Python packages. There is not really much human language in there, and they're not intended for consumption by humans anyways.

**Comment by bluebird75** [comment]
Maybe you talk about the error messages reported by the code checking tool like mypy ?
 
Anyway, the stubs are developed in the Python language. It's as monolingual but you are expecting to understand it if you develop in Python.
