### ISSUE TITLE
stubs 5.13 is incompatible with pyqt5 5.14.1

### ISSUE THREAD

**Issue by tenone11** [stlehmann/PyQt5-stubs#24]
Hi, Guys

Hope you are very well.
I setup PYQT5 and then PYCHARM recomend me to setup pyqt5-stubs.
I think it was a good way for me. So setup automaticlly from pycharm
Then I open pycharm again, below picture show at pycharm top.

Could you please reply me the solution?
Maybe the different version, I guess:) Looking forward your update
![error](https://user-images.githubusercontent.com/52339115/73519464-27855f00-443c-11ea-91d1-8d67194407c6.PNG)

**Comment by stlehmann** [comment]
Yes, PyQt5.14 has been out now for a while. I didn't manage to provide an update, yet. I'll try to publish one this weekend.

**Comment by tenone11** [comment]
Hard work guy!
Thanks a lot

**Comment by BryceBeagle** [comment]
What's the status of the 5.14 release? Is there a list of tasks that need to be done before release?
