### ISSUE TITLE
Support PyQt5-commercial

### ISSUE THREAD

**Issue by james-emerton** [stlehmann/PyQt5-stubs#25]
As a PyQt5 licensee, the package we install is called `PyQt5-commercial`. This creates a bit of trouble installing this package as it depends on `PyQt5`; the non-commercial (but otherwise identical) variant of PyQt.

Is it feasible to simply drop PyQt5 from `install_requires`, or could we choose between commercial/GPL versions using `extras_require`?

**Comment by The-Compiler** [comment]
I wonder if we the stubs depend on `PyQt5` at all. Given that the stubs will always lag behind a bit for newer PyQt releases, but are perfectly usable (as long as no new API is used), I feel like we should just let users handle that dependency manually.

Also, if I just want to run mypy, wouldn't it suffice to have the stubs installed without PyQt5 being installed at all?

**Comment by stlehmann** [comment]
> I wonder if we the stubs depend on PyQt5 at all. Given that the stubs will always lag behind a bit for newer PyQt releases, but are perfectly usable (as long as no new API is used), I feel like we should just let users handle that dependency manually.

We can give this a thought. This would definetely take away much pressure of releasing new versions. I thought it to be actually good practice to include the source package of a stub in the requirements. But it might not be necessary and in this case even counter-productive.

**Comment by stlehmann** [comment]
@james-emerton Is this one solved by now? Then the issue can be closed.

**Comment by The-Compiler** [comment]
> We can give this a thought. This would definetely take away much pressure of releasing new versions. I thought it to be actually good practice to include the source package of a stub in the requirements. But it might not be necessary and in this case even counter-productive.

That seems to be the case in general, yeah - [PEP 561](https://www.python.org/dev/peps/pep-0561/) says:

> In addition, stub-only distributions SHOULD indicate which version(s) of the runtime package are supported by indicating the runtime distribution's version(s) through normal dependency data. For example, the stub package flyingcircus-stubs can indicate the versions of the runtime flyingcircus distribution it supports through install_requires in distutils-based tools, or the equivalent in other packaging tools. Note that in pip 9.0, if you update flyingcircus-stubs, it will update flyingcircus. In pip 9.0, you can use the --upgrade-strategy=only-if-needed flag. In pip 10.0 this is the default behavior.

But like you say, in this case it probably has more downsides than benefits, so let's see how things go without it.

**Comment by james-emerton** [comment]
> @james-emerton Is this one solved by now? Then the issue can be closed.

I haven't had a chance to test this, but I'm pretty confident this change will solve my problem. Thanks!
