### ISSUE TITLE
Handling self.parent()

### ISSUE THREAD

**Issue by karlch** [stlehmann/PyQt5-stubs#27]
I often use `self.parent()` knowing that the parent is of some specific type which has more logic than a simple `QObject`. In these cases mypy rightfully complains like so:
```
error: "QObject" has no attribute "width"  [attr-defined]
```
but of course in this case the parent is some type of `QWidget` which does have a `width`.

Solutions I thought of are:
* Overriding `parent` in the child class just for the sake of type hinting with a `cast`
* Explicitly keeping the parent as an attribute in the child

Both seem a bit redundant to me. Just adding `# type: ignore` to all of these calls is also somewhat sub-optimal.

Do you have any recommendations?

Thanks in advance and thanks once again for all the work you have done here!

**Comment by The-Compiler** [comment]
At least for the case you described, this should be solvable in the stubs: A QWidget's parent always needs to be a QWidget as well (and e.g. its `setParent()` method is overwritten accordingly).

**Comment by karlch** [comment]
That sounds great, thanks for the super fast response!

And in case a custom class with some custom method is used, which is by far less often, at least for me, one could still fallback to one of the options outlined before. Or do you have another better recommendation?

**Comment by The-Compiler** [comment]
Indeed! Another solution I can think of is having a custom method, i.e. something like:

```python3
def tabwidget(self):
    return typing.cast(QTabWidget, self.parent())
```

I'd probably prefer that or a custom attribute in that case - that way, you have an idea what the code does/gets exactly without having to keep the object tree in your head. If you see something like `self.parent().count()` in a widget, that doesn't say much, while `self.tabwidget().count()` or `self.tabwidget.count()` is much clearer.

In addition to readability, it's probably also easier to test (where you might want to pass a different parent or none at all) and easier to handle when refactoring (when the parent changes, but you still want to e.g. access the tabwidget, which might now be something like `.parent().parent()`).

**Comment by karlch** [comment]
Sounds good, thanks again for your time and comments!

I will keep this open for the sake of the part relating to the parent of a `QWidget` always being a `QWidget`. If this only involves overriding `QWidget.parent()` in the stubs, I could also open a PR somewhen later next week.
