### ISSUE TITLE
Does this repository have the correct license?

### ISSUE THREAD

**Issue by BryceBeagle** [stlehmann/PyQt5-stubs#37]
PyQt is licensed under the GPL (unless you have a commercial license).

Would the generated stubs not need to be distributed under the same license? I'm not sure the MIT license is valid to distribute them.

**Comment by stlehmann** [comment]
Hm, indeed this might be an issue. Normally I use MIT license for all my project. But in this case this might be a problem. I agree with you that it might be better to change the license to comply with the PyQt5 licensing model. As I understand it PyQt5 is licensed under LGPL and GPL. I would vote to go for LGPL. However I am not experienced with licensing. @BryceBeagle and @The-Compiler what are your thoughts on this?

**Comment by BryceBeagle** [comment]
Unfortunately the only two licensing options for PyQt are GPL and commercial, not LGPL:
https://www.riverbankcomputing.com/commercial/license-faq

You can see at the top of the generated .pyi files that they're licensed under the GPL.

My understanding of the GPL license means that if the source is licensed under GPL, patch files need to be too -- they contain bits of the original source, afterall. But I am definitely not a lawyer and I know these things can be tricky.

**Comment by stlehmann** [comment]
Ah OK I got a bit mixed up because they refer to the LGPL version of Qt. I actually wouldn' t mind changing the license to GPL. This would save us some trouble and one can not use the stubs without the source anyway. So there would be no negative effects of the more constrained GPL.

**Comment by stlehmann** [comment]
This issue should be solved with #38
