### ISSUE TITLE
QCoreApplication aboutToQuit not defined as signal

### ISSUE THREAD

**Issue by karlch** [stlehmann/PyQt5-stubs#4]
First of all thanks a bunch for your work on this!

When connecting to the `aboutToQuit` signal in `QCoreApplication` mypy complains with:
```
"Callable[[], None]" has no attribute "connect"
```

I suspect this is because it is simply defined as a function in the stub, not as a signal. Is there any reason for this or could this be changed?

**Comment by stlehmann** [comment]
Thanks for the feedback. The upstream PyQt5 stubs type-annotate signals as functions. They need to be changed to the type *pyqtSignal*. I will change this right away. If you discover any more such issues feel free to make a PR or report.

**Comment by stlehmann** [comment]
Fixed with 9e7cbb938ba097a55cbb7aaf8de23170a54dce1d

**Comment by karlch** [comment]
Perfect, thanks!

**Comment by 3rdcycle** [comment]
> Fixed with [9e7cbb9](https://github.com/stlehmann/PyQt5-stubs/commit/9e7cbb938ba097a55cbb7aaf8de23170a54dce1d)

Wait, am I missing something here? This provided a fix for `applicationVersion` but none of the other signals including the one originally requested (`aboutToQuit`)? As far as I can see most signal stubs are still simple `def`s.

**Comment by stlehmann** [comment]
You are right. There went something wrong, here. I'll have a look at it.

**Comment by 3rdcycle** [comment]
That was quick 😃 thanks.
