### ISSUE TITLE
PyQt5 wheels will be shipped with stubs in the future

### ISSUE THREAD

**Issue by The-Compiler** [stlehmann/PyQt5-stubs#40]
According to the PyQt mailinglist, the next PyQt release will ship wheels with its own stubs:

https://www.riverbankcomputing.com/pipermail/pyqt/2020-April/042854.html

My first thought was "hey, cool, so we don't need to build anything to get the stubs files!" (cc @BryceBeagle)... However, my second thought was "wait a minute... what will happen when people have both PyQt5 and PyQt5-stubs installed"? No idea which of the two will take precedence then, even after [reading the relevant part of the PEP](https://www.python.org/dev/peps/pep-0561/#type-checker-module-resolution-order) I don't understand what precedence stubs as part of the installed package (i.e. not inline types) have...

**Comment by stlehmann** [comment]
That will be interesting to see. I'm also curious what quality those stub files will have.

**Comment by The-Compiler** [comment]
> I'm also curious what quality those stub files will have.

I'm guessing they will be the files `sip` already generates.

**Comment by stlehmann** [comment]
> I'm guessing they will be the files sip already generates.

So it will still be necessary to elaborate them for the PyQt5-stubs packages. But it makes no sense if the PyQt5 stubs take precedence over our stubs. This might render this package useless.

**Comment by BryceBeagle** [comment]
I'm pleased that the wheels will begin to ship with stubs! A little disappointing that my build script will get deprecated so quickly though, haha.

**Comment by stlehmann** [comment]
Let's see how it works out with the new stubs. Until now they needed heavy refactoring from our side to be of any use.

**Comment by altendky** [comment]
Having minimally looked over these stubs and the upstream what I have in my head is to get our master fixed up a bit (tests passing?  `:]`) and then talk to Phil about how he might be interested in working through the differences.

**Comment by altendky** [comment]
FYI, shared the work here with Phil.  My feeling is that we'll have to break it down or submit patches, but perhaps I'm misreading.

https://www.riverbankcomputing.com/pipermail/pyqt/2020-October/043291.html

**Comment by bluebird75** [comment]
To answer one of the initial questions, if you install pyqt5-stubs, our stubs take precedence over the stubs shipped directly with PyQt5 . This is a good thing for us, although slithly surprising for me.

Submitting our improvements as patches could certainly be done. But since the other stubs are generated, this will cerainly complicate the generation process for Phil. We shall see when we do it.

**Comment by bluebird75** [comment]
The process is now to use the pyqt5 wheel as sources for the stubs and merge them with our work. Closing this issue.
