### ISSUE TITLE
Flags class should annotate __or__() function

### ISSUE THREAD

**Issue by AlexGuo1998** [stlehmann/PyQt5-stubs#52]
When I write something like
```python
file.open(QtCore.QFile.ReadOnly | QtCore.QFile.Text)
```
It just gives me a warning `Unexpected type: int`.

Flags like `QIODevice.OpenModeFlag` can be or-ed together. So I suggest annotating the `__or__()` function to suppress this warning.

According to the Qt documentation:
"The `OpenMode` type is a typedef for `QFlags<OpenModeFlag>`. It stores an OR combination of `OpenModeFlag` values."
We should annotate `OpenModeFlag` like this:

```python
class QIODevice(QObject):
    class OpenModeFlag(int):
        def __or__(self, other: typing.Union['QIODevice.OpenModeFlag', 'QIODevice.OpenMode']) -> 'QIODevice.OpenMode': ...
```

And this should be done for `OpenMode` too.
```python
class QIODevice(QObject):
    ...
    class OpenMode(sip.simplewrapper):
        ...
        def __or__(self, other: typing.Union['QIODevice.OpenModeFlag','QIODevice.OpenMode']) -> 'QIODevice.OpenMode': ...
```

**Comment by Djedouas** [comment]
Good idea, same for `QMessageBox.StandardButton` enum, `QMessageBox.StandardButtons` flags, `QDialogButtonBox.StandardButton` enum, `QDialogButtonBox.StandardButtons` flags, and surely other enum among Qt

**Comment by stlehmann** [comment]
@AlexGuo1998 great idea. Would you like to create a PR for this issue?

**Comment by AlexGuo1998** [comment]
> @AlexGuo1998 great idea. Would you like to create a PR for this issue?

Sure. But later once I have enough time.

**Comment by BryceBeagle** [comment]
Probably also want to make sure to support the other bitwise operators that [QFlags](https://doc.qt.io/qt-5/qflags.html) implements. `__and__`, `__xor__`, `__ior__`, `__iand__`, etc

**Comment by Djedouas** [comment]
I've just run into a simillar problem, in fact no operator overload is present in the stubs.
I had to add the `__mul__` overload for `QSizeF` to support float... ([doc](https://doc.qt.io/qt-5/qsizef.html#operator-2a-eq))

That's a big work... are operator overloads more difficult to automatize than standard methods?

**Comment by AlexGuo1998** [comment]
Not sure how "upstream stubs" are built... I guess there's something to do with that.

**Comment by BryceBeagle** [comment]
The upstream stubs can be built using the [`Dockerfile`](https://github.com/stlehmann/PyQt5-stubs/blob/master/Dockerfile) at the root of the project

There's a [script](https://github.com/stlehmann/PyQt5-stubs/blob/master/build_upstream.py) to make this convenient, and the [README](https://github.com/stlehmann/PyQt5-stubs/blob/master/README.md#building-upstream-stubs) discusses how to use it.

**Comment by stlehmann** [comment]
> That's a big work... are operator overloads more difficult to automatize than standard methods?

@Djedouas I honestly can not tell you. This repository just takes the autogenerated stubs from PyQt5 build and adds missing annotations or fixes broken ones. All of this is done by hand at the moment. So feel free to add a PR with your changes even if they are not comprehensive. Each contribution adds to the overall usability of PyQt5-stubs.
