### ISSUE TITLE
Incomplete typing for QGraphicsItem.itemChange() ?

### ISSUE THREAD

**Issue by TilmanK** [stlehmann/PyQt5-stubs#53]
I wanted to clarify things before submitting a PR.

The current implementation in the stubs for QGraphicsItem.itemChange is as follows:
`    def itemChange(self, change: 'QGraphicsItem.GraphicsItemChange', value: typing.Any) -> typing.Any: ...`

The Qt documentation defines type of value and the return value as QVariant:
https://doc.qt.io/qt-5/qgraphicsitem.html#itemChange

How are you handling QVariants in your code? I know that the usage of QVariant is a little strange (i.e. when putting a str into a QVariant, this returns a str).

**Comment by The-Compiler** [comment]
Those stubs are coming directly from PyQt5 upstream as far as I'm aware. I think `typing.Any` is the right thing to use for a `QVariant` as it's effectively an union over various different types, i.e. too dynamic to be typed. Do you have any concrete improvement in mind I didn't think of?

**Comment by TilmanK** [comment]
Well, I'm directly annotating it as a QVariant in a reimplementation and I'm also using a QVariant. The point is, there are two ways of  i.e. returning an Integer:

return 5

return QVariant(5)

And I'm still unsure, which one should be the correct or preferred way.

**Comment by The-Compiler** [comment]
If both are possible, it'd be wrong for the type annotation to claim that the return value must be a QVariant. I think it's fine to rely on the automatic conversion and only use an explicit QVariant if it's really needed to override it for some reason. Also see the upstream docs: [Support for QVariant — PyQt v5.15.0 Reference Guide](https://www.riverbankcomputing.com/static/Docs/PyQt5/pyqt_qvariant.html)
