### ISSUE TITLE
Widen PyQt5 dependency to 5.*

### ISSUE THREAD

**Issue by bluebird75** [stlehmann/PyQt5-stubs#55]
I understand that it is quite cumbersome to track all the releases (major and minor) of PyQt5 and keep this stub package up-to-date from a pip dependency point of view.

However, if you think about it : 
* all versions of PyQt5 and Qt5 are backward compatible.
* so, a stub file valid for PyQt 5.13 will also be useful and valid for 5.12 . Maybe there are a few extra methods but that's a small issue
* also, a stub file valid for PyQt 5.13 is certainly useful and valid for PyQt 5.14 and 5.15 . Same story, a few new methods or objects could be missing but that's about 0.01% of the codebase.

So my suggestion : declare PyQt5 5.* as a dependency. 

This means that basically every user of PyQt5 can take advnatage of the stubs, whatever the version he is using. It means more potential contributors !

**Comment by stlehmann** [comment]
@bluebird75 Those are valid points. We already have the problem that we can not provide a full set of correct stubs and it is always work in progress. From my point of view I think we could widen the dependency restriction. @The-Compiler what do you think?

**Comment by stlehmann** [comment]
@bluebird75 feel free to drop a PR.

**Comment by The-Compiler** [comment]
Sounds reasonable! :+1:

**Comment by bluebird75** [comment]
Ok, I'll do it.

By the way, great work for the stubs !

**Comment by bluebird75** [comment]
I looked into it but actually, PyQt5-stubs does not define any install dependency, so we can already install it with any version of PyQt5 . It seems that only the testing requires a specific version of PyQt5.

What do you expect me to do then ? Add a install_require entry in setup.py ?

**Comment by BryceBeagle** [comment]
I don't think any of the tests actually require `PyQt5==5.14.*` specifically. We can probably just widen the PyQt5 version in the `tests_require` field too.

**Comment by altendky** [comment]
If there are no dependencies then what needs to be fixed?  @bluebird75, what problem did you have that resulted in submitting this issue?  Just want to make sure we know what we can improve for you.

As for testing, it seems to me that would be about running testing in CI against however many versions and on however many OSes we are interested in.  I haven't gotten around to looking at the test setup here yet but the `test` command that uses `tests_require` is deprecated so I would more expect that to go away than to get maintained.  Unless I've got something wrong here?

https://setuptools.readthedocs.io/en/latest/setuptools.html
> New in 41.5.0: Deprecated the test command.

**Comment by bluebird75** [comment]
Specifically,I was using PyCharm and I don't remember what I did exactly. But PyCharm told me it had uninstalled PyQt5.15 to install PyQt 5.14 to be compatible with the stubs.

This gave me the impression that PyQt5-stubs was version constrainted but that's actually wrong. Maybe it's just a PyCharm thing.

The version naming of PyQg5-stubs also gives this impression.

**Comment by altendky** [comment]
I do use PyCharm but I'm just starting into hints really so I've ignored most anything that PyCharm says about them.  :]  I also manage my envs outside PyCharm.  But, I did just update to PyCharm 2020.2.2 and created a new project and let it create an env and installed PyQt5 5.15.1 and then PyQt5-stubs 5.14.2.2 and it didn't complain.

Also, we're presently working to get PyQt5-stubs updated with the 5.15.0 and 5.15.1 changes so the version number is representative of the 5.14.2 stubs the present release is based on.

If you can recreate the issue I'll see if I can make it happen here.

**Comment by The-Compiler** [comment]
FWIW I think this was already fixed in 02a0b6174ff6c7c6ca9f982947b8698c34c85537.

**Comment by altendky** [comment]
Quite so, and in response to #25 (for the linkage).  I forgot to even bother to look at the history, thanks.  FWIW, I do use `extras_require` in other projects so that version restrictions can be enforced but only at the user's request and I keep wishing that there was an `install_constraints` that could be specified instead.  But I suspect this would make more sense if we someday end up creating per-PyQt-version releases that are back-maintained.  Such as if actual stub generation is created and when we update the generator we re-release updates to old PyQt releases.  But that's some future someday...  `:]`

**Comment by altendky** [comment]
Should we close this?  @bluebird75, does your need seem to have been addressed?  The linked change should be present from 5.14.1.0 released April 3, 2020.

**Comment by bluebird75** [comment]
Yet, it's been already addressed. Great work by the way !
