### ISSUE TITLE
Lock master and upstream branches

### ISSUE THREAD

**Issue by altendky** [stlehmann/PyQt5-stubs#80]
Do we have the master branch locked down?  I like it to be locked both to avoid accidents and force PRs so there is review.  Depending on the release workflow there can be conflicts, but...  Opinions?  Once we get CI passing we can require it to pass for merges as well.  Oh, probably both master and upstream in the case of this repo.

**Comment by BryceBeagle** [comment]
I'm a fan of locking main-line branches and enforcing the PR workflow

**Comment by altendky** [comment]
Now we've got `master` green in CI, we probably mostly want to keep it that way?  So the branch could be set to require Travis passing.  @stlehmann, opinions?  `upstream` could be locked from direct pushes but is expected to fail CI (unless we adjust it) so it wouldn't get set to require Travis passing.

**Comment by altendky** [comment]
Oh yeah, I also like requiring that PR branches are up to date.  Bonus, this gets you a button on the PR page to have GitHub do the update merge for you easily.

**Comment by bluebird75** [comment]
So, if everybody here agrees that it's a good idea to lock master, I guess you can take care of it ...

**Comment by bluebird75** [comment]
This seems no longer relevant. closing
