### ISSUE TITLE
Please add support for indexing pyqtSignal Objects.

### ISSUE THREAD

**Issue by deavid** [stlehmann/PyQt5-stubs#9]
https://github.com/stlehmann/PyQt5-stubs/blob/189a0497d08ddd65f46e4819f427eb2d03196589/PyQt5-stubs/QtCore.pyi#L31

See this link:
https://stackoverflow.com/questions/45337136/qsignalmapper-in-pyqt5-not-working-when-the-function-argument-is-a-str

We're expected to do: "mapper.mapped[str].connect(a_function)" in order to retrieve the overload we want for the signal.
 
It should be enough if we add __getitem__ returning pyqtSignal.

**Comment by BryceBeagle** [comment]
Was this implemented? I still see pyqtSignals as not indexable

```python
class CoolClass(QObject):
    signal = pyqtSignal([int], [str])

    def __init__(self) -> None:
        super().__init__()
        self.signal[int].connect(lambda val: print(val))
        self.signal[str].connect(lambda val: print(val[::-1]))


instance = CoolClass()
instance.signal[int].emit(5)
instance.signal[str].emit("five")
```

```
tests/pyqtslot.py:16: error: Value of type "pyqtSignal" is not indexable
tests/pyqtslot.py:17: error: Value of type "pyqtSignal" is not indexable
tests/pyqtslot.py:21: error: Value of type "pyqtSignal" is not indexable
tests/pyqtslot.py:22: error: Value of type "pyqtSignal" is not indexable
Found 4 errors in 1 file (checked 1 source file)


tests/test_stubs.py:14 (test_stubs[pyqtslot.py])
filename = 'pyqtslot.py'

    @pytest.mark.parametrize('filename', list(gen_tests()))
    def test_stubs(filename):
        """Run mypy over example files."""
        path = os.path.join(TESTS_DIR, filename)
        stdout, stderr, exitcode = api.run([path])
        if stdout:
            print(stdout)
    
>       assert stdout.startswith("Success: no issues found")
E       assert False
E        +  where False = <built-in method startswith of str object at 0x7f7d90cffcb0>('Success: no issues found')
E        +    where <built-in method startswith of str object at 0x7f7d90cffcb0> = 'tests/pyqtslot.py:16: error: Value of type "pyqtSignal" is not indexable\ntests/pyqtslot.py:17: error: Value of type ...pyqtslot.py:22: error: Value of type "pyqtSignal" is not indexable\nFound 4 errors in 1 file (checked 1 source file)\n'.startswith

tests/test_stubs.py:23: AssertionError
```

**Comment by stlehmann** [comment]
No this has not been implemented, yet. I closed it because it was an old issue. As it is not a feature I am using I must admit that I didn't have a close look at it. But did so now. I think that's definetly a thing we could do.

**Comment by stlehmann** [comment]
@BryceBeagle would you like to take care of it?

**Comment by altendky** [comment]
I just added `pyqtBoundSignal.__getitem__()` as suggest by the OP in the OP to #56.  I could be talked into making it a separate follow-up PR if people find the two changes sufficiently unrelated.

**Comment by altendky** [comment]
#56 is merged.  @deavid, does that look like it does what you wanted?  It doesn't implement anything as to the actual types but it should at least let you go through the motions unchecked and without complaint.

**Comment by deavid** [comment]
Hi, I moved away from the original project that required this and @Aulla is on it at the moment. Maybe he can comment here. For now, I'll just close this.
